name: dymenz
favicon: null
layout_spectrum: 0.9350182346533984
typography_spectrum: 0.5048868460580707
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9843400011304766
  lightness: 0.7886791166383773
  saturation: 0.5640875650569797
  rhythmicContrast: 0.780086105922237
purpose: []
